### ISSUE TITLE
local variable 'currentblock' referenced before assignment

### ISSUE THREAD

**Issue by suede299** [hako-mikan/sd-webui-lora-block-weight#49]
![屏幕截图 2023-04-22 161457](https://user-images.githubusercontent.com/85022330/233772045-75998d7d-4a52-4311-9abe-077b77a0a564.jpg)
Using either of the following methods will return the same error result
![屏幕截图 2023-04-22 161351](https://user-images.githubusercontent.com/85022330/233772082-98274ded-df30-4776-9ce2-ddd4526055db.jpg)

*Installed the a1111-sd-webui-locon extension

**Comment by hako-mikan** [comment]
This error occurs when using an incompatible LoRA.
try to update a1111-sd-webui-locon or use a1111-sd-webui-Lycorys

**Comment by drhead** [comment]
I get this error when trying to use SD2.1-based LoRAs -- I am certain that Lycoris and this extension are both updated and Lycoris itself loads the model just fine.  Such a shame too, since I was getting excellent results when using block weights... is there any chance that SD2.1 LoRAs could be made compatible if that is the issue?

**Comment by hako-mikan** [comment]
I see what you mean, I understood, and as for LoRA in the SD-2.1 series, I did not try it, so I will get it and give it a try. Thanks.

**Comment by hako-mikan** [comment]
I could not reproduce the problem. 
If you still have the problem, please let me know your environment.
